bold = true
color_mode = "rgb"
palette = "default" # default, darker, pastel, matrix
rainbow = 10 # 0 - 255
delay_ms = 20
inherit_style = false
kinds = ["curved"] # heavy, light, curved, knobby, emoji, outline, dots, blocks, sus
num_pipes = 2
reset_threshold = 0.5 # 0.0-1.0
turn_chance = 0.15 # 0.0-1.0
